pool:
  vmImage: 'windows-latest'

steps:
- script: dotnet --list-sdks
  displayName: 'show sdks available'

- script: dotnet --list-runtimes
  displayName: 'show runtimes available'

- script: build.bat
  displayName: 'Run build and tests'

- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: 'test/*/TestResults/*.trx' 
    failTaskOnFailedTests: true

