pool:
  vmImage: 'windows-latest'

trigger:
  tags:
    include:
    - v*

steps:
- script: build.bat
  displayName: 'Run build and tests'

- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: 'src/*/*.csproj'

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    allowPackageConflicts: true