pool:
  vmImage: 'windows-latest'

trigger:
  tags:
    include:
    - v*

steps:
- task: UseDotNet@2
  displayName: Make sure .NET 2.0.x is installed
  inputs:
    packageType: runtime
    version: 2.0.*

- task: UseDotNet@2
  displayName: Make sure .NET 2.2.x is installed
  inputs:
    packageType: runtime
    version: 2.2.*

- script: pack-push.bat
  displayName: 'Pack and push'

