pool:
  vmImage: 'windows-latest'

trigger:
  tags:
    include:
    - v*

steps:

- script: echo $(api_key)
  displayName: 'Pack and pushx'

- script: pack-push.bat $(api_key)
  displayName: 'Pack and push'

