pool:
  vmImage: 'windows-latest'

trigger:
  tags:
    include:
    - v*

- task: UseDotNet@2
  displayName: Make sure .NET 2.0.x is installed
  inputs:
    packageType: runtime
    version: 2.0.*

- task: UseDotNet@2
  displayName: Make sure .NET 2.2.x is installed
  inputs:
    packageType: runtime
    version: 2.2.*

steps:
- script: build.bat
  displayName: 'Run build and tests'

- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: 'src/*/*.csproj'

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    allowPackageConflicts: true